### PR TITLE
Week nine

### LINKED ISSUE #5: Jack Goes To Rapture
[Problem Link](https://www.hackerrank.com/challenges/jack-goes-to-rapture)

### PR DESCRIPTION
**Pull request by isaac-gs**
Hey look it's another PR that closes #5

### CODE REVIEW

**Review by asclines — APPROVED** [review]
Overall looks really clear, clean and good. Liked how you referenced your source for the UF structure. However, this bring up a point that has yet to be brought up. That UF structure is very generic. Do we want to create a sort of codebase for common code like this to not only separate certain logic from implementation, but also to provide a good cookbook that people can bring in for future problems?

**Comment by isaac-gs** [comment]
@asclines That might be good to add if we keep contributing to this, but I wouldn't prioritize that just yet. On the other hand, I might keep contributing to this as practice.

**Comment by asclines** [comment]
@ASAAR I agree, I am in no way prioritizing it, or expecting anything to happen before the end of the semester about that. But I would like to see this repo grow and continue beyond this semester, so im adding my thoughts in now (while I still remember them) for fuel for thought and for later reference.

**Comment by isaac-gs** [comment]
@asclines then absolutely agree. Just proactively warding off additional work until this semester is done :)

**Pull request merged**
